### PR TITLE
Updates to the GPU stdlib PR

### PR DESCRIPTION
**Pull request by powerjg**
Here are some updates to your PR to clean things up from my end. This was co-authored with @mahyarsamani @mbabaie and @Harshil2107.

I didn't want to directly push to your PR on gem5, but if you think this looks good, I can push there.

Also, I did *some* testing (I ran a simple example), and I also tested using the `cpu_cache_hierarchy` with the x86 board (that works now!).

Let me know if you have any questions about my updates. I'll be at MICRO next week, but I should be checking email.

Thanks again for all of your effort on this change!!!

### CODE REVIEW

**Comment by abmerop** [comment]
The AVX commit should be rebased so that only src/python/gem5/prebuilt/viper/board.py is modified. There are a few bug fixes being reverted.

I am curious how HBM stack works.  It looks like there is only one directory now.  Do you not see massive contention at the directory and/or the network links to that directory?  What is the bandwidth like?

**Comment by powerjg** [comment]
Ah yes, that commit is what's causing the conflicts. I can fix that. 

> I am curious how HBM stack works. It looks like there is only one directory now. Do you not see massive contention at the directory and/or the network links to that directory? What is the bandwidth like?

@mahyarsamani Can you answer this? My intention was to have 1-to-1 directories and memory controllers. If that's not the case, we need to fix it.

**Comment by mahyarsamani** [comment]
> Ah yes, that commit is what's causing the conflicts. I can fix that. 
> 
> 
> 
> > I am curious how HBM stack works. It looks like there is only one directory now. Do you not see massive contention at the directory and/or the network links to that directory? What is the bandwidth like?
> 
> 
> 
> @mahyarsamani Can you answer this? My intention was to have 1-to-1 directories and memory controllers. If that's not the case, we need to fix it.

I believe there should be one directory per memory port. In the case of HBMStack there are 8 ports.

**Comment by abmerop** [comment]
> > Ah yes, that commit is what's causing the conflicts. I can fix that.
> > 
> > 
> > @mahyarsamani Can you answer this? My intention was to have 1-to-1 directories and memory controllers. If that's not the case, we need to fix it.
> 
> I believe there should be one directory per memory port. In the case of HBMStack there are 8 ports.

Oh yes, sorry you are correct- The way the diff was presented I did not notice the directories were within a for loop.

**Comment by powerjg** [comment]
We also tested and saw memory accesses to all memory controllers, so that's a good sign. I'm excited to run something like stream to see if we finally can fix the bandwidth issue that Matt S has talked about

**Comment by powerjg** [comment]
Sigh... rebase hell... I think I'll wait until tomorrow to try to clean this up. I'm sorry for the confusion.

Tomorrow, I'll just push this to the PR on gem5/gem5

**Comment by abmerop** [comment]
Rebased in main repo.

**Comment by mattsinc** [comment]
> We also tested and saw memory accesses to all memory controllers, so that's a good sign. I'm excited to run something like stream to see if we finally can fix the bandwidth issue that Matt S has talked about

We have Babelstream running in gem5 locally that we can work to push publicly if it would help.  We are also working on pushing the updates to the GPU HBM leveraging Ayaz's work -- right now there is a problem when merging with the head of develop we're working though (after fixing the merge issue, now there is a performance bug ...).  In any event, those are coming although I don't think they will directly relate to stdlib as they are focused on main memory.

**Pull request closed without merging**
